[package]
name = "async-perf-events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perf-event = "0.4.7"
tokio = { version = "1.14.0", features = ["full"] }
tracing = "0.1.29"

[features]
